"""initial_tables

Revision ID: 1abf9828413a
Revises: 
Create Date: 2026-03-26 20:43:07.365971

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1abf9828413a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('riders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('vehicle_type', sa.Enum('bike', 'car', 'van', name='vehicletype'), nullable=False),
    sa.Column('status', sa.Enum('available', 'on_route', 'offline', name='riderstatus'), nullable=False),
    sa.Column('current_lat', sa.Float(), nullable=True),
    sa.Column('current_lon', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_riders_id'), 'riders', ['id'], unique=False)
    op.create_table('road_conditions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('from_node', sa.String(length=100), nullable=False),
    sa.Column('to_node', sa.String(length=100), nullable=False),
    sa.Column('blocked', sa.Boolean(), nullable=False),
    sa.Column('weight_multiplier', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_road_conditions_from_node'), 'road_conditions', ['from_node'], unique=False)
    op.create_index(op.f('ix_road_conditions_id'), 'road_conditions', ['id'], unique=False)
    op.create_index(op.f('ix_road_conditions_to_node'), 'road_conditions', ['to_node'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('admin', 'dispatcher', name='userrole'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('deliveries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('address', sa.Text(), nullable=False),
    sa.Column('lat', sa.Float(), nullable=False),
    sa.Column('lon', sa.Float(), nullable=False),
    sa.Column('priority', sa.Enum('low', 'medium', 'high', name='deliverypriority'), nullable=False),
    sa.Column('status', sa.Enum('pending', 'assigned', 'in_transit', 'delivered', 'failed', name='deliverystatus'), nullable=False),
    sa.Column('rider_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['rider_id'], ['riders.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_deliveries_id'), 'deliveries', ['id'], unique=False)
    op.create_index(op.f('ix_deliveries_rider_id'), 'deliveries', ['rider_id'], unique=False)
    op.create_table('routes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('rider_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('draft', 'active', 'completed', 'cancelled', name='routestatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['rider_id'], ['riders.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_routes_id'), 'routes', ['id'], unique=False)
    op.create_index(op.f('ix_routes_rider_id'), 'routes', ['rider_id'], unique=False)
    op.create_table('algorithm_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('route_id', sa.Integer(), nullable=False),
    sa.Column('algorithm_name', sa.String(length=50), nullable=False),
    sa.Column('distance_km', sa.Float(), nullable=True),
    sa.Column('duration_min', sa.Float(), nullable=True),
    sa.Column('nodes_explored', sa.Integer(), nullable=True),
    sa.Column('runtime_ms', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['route_id'], ['routes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_algorithm_runs_id'), 'algorithm_runs', ['id'], unique=False)
    op.create_index(op.f('ix_algorithm_runs_route_id'), 'algorithm_runs', ['route_id'], unique=False)
    op.create_table('route_stops',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('route_id', sa.Integer(), nullable=False),
    sa.Column('delivery_id', sa.Integer(), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['delivery_id'], ['deliveries.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['route_id'], ['routes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_route_stops_delivery_id'), 'route_stops', ['delivery_id'], unique=False)
    op.create_index(op.f('ix_route_stops_id'), 'route_stops', ['id'], unique=False)
    op.create_index(op.f('ix_route_stops_route_id'), 'route_stops', ['route_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_route_stops_route_id'), table_name='route_stops')
    op.drop_index(op.f('ix_route_stops_id'), table_name='route_stops')
    op.drop_index(op.f('ix_route_stops_delivery_id'), table_name='route_stops')
    op.drop_table('route_stops')
    op.drop_index(op.f('ix_algorithm_runs_route_id'), table_name='algorithm_runs')
    op.drop_index(op.f('ix_algorithm_runs_id'), table_name='algorithm_runs')
    op.drop_table('algorithm_runs')
    op.drop_index(op.f('ix_routes_rider_id'), table_name='routes')
    op.drop_index(op.f('ix_routes_id'), table_name='routes')
    op.drop_table('routes')
    op.drop_index(op.f('ix_deliveries_rider_id'), table_name='deliveries')
    op.drop_index(op.f('ix_deliveries_id'), table_name='deliveries')
    op.drop_table('deliveries')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_road_conditions_to_node'), table_name='road_conditions')
    op.drop_index(op.f('ix_road_conditions_id'), table_name='road_conditions')
    op.drop_index(op.f('ix_road_conditions_from_node'), table_name='road_conditions')
    op.drop_table('road_conditions')
    op.drop_index(op.f('ix_riders_id'), table_name='riders')
    op.drop_table('riders')
    # ### end Alembic commands ###
