"""add email to riders

Revision ID: a5726b6577b5
Revises: f1a1967b6f04
Create Date: 2026-03-31 20:22:02.664367

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a5726b6577b5'
down_revision: Union[str, Sequence[str], None] = 'f1a1967b6f04'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('riders', sa.Column('email', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('riders', 'email')
    # ### end Alembic commands ###
