"""set default values for delivery_fee and notes

Revision ID: aecd9fb9fc2f
Revises: b06574635461
Create Date: 2026-03-31 15:39:26.197494

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aecd9fb9fc2f'
down_revision: Union[str, Sequence[str], None] = 'b06574635461'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("UPDATE deliveries SET delivery_fee = 500.0 WHERE delivery_fee IS NULL")
    op.alter_column('deliveries', 'delivery_fee',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('deliveries', 'delivery_fee',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    # ### end Alembic commands ###
