"""add transactions and delivery_fee

Revision ID: b06574635461
Revises: 8aa4ea231475
Create Date: 2026-03-31 11:59:15.810929

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b06574635461'
down_revision: Union[str, Sequence[str], None] = '8aa4ea231475'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('deliveries', sa.Column('delivery_fee', sa.Float(), nullable=False))
    op.add_column('deliveries', sa.Column('notes', sa.Text(), nullable=True))
    op.add_column('deliveries', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('deliveries', 'updated_at')
    op.drop_column('deliveries', 'notes')
    op.drop_column('deliveries', 'delivery_fee')
    # ### end Alembic commands ###
